### ISSUE TITLE
Could you credit my name for the 'nomad-coin' ?

### ISSUE THREAD

**Issue by ruucm-working** [serranoarevalo/nomadcoin#1]
:)

**Comment by serranoarevalo** [comment]
@ruucm-working I don't know what you mean by 'credit my name'

**Comment by ruucm-working** [comment]
haha credit for 'movie closing credits'
I just thought yesterday talking about the coin idea of nomad codders.

If it doesn't really needed in your thought you can just close it~

**Comment by serranoarevalo** [comment]
hahaha I didn't know who you were man! I got it now hahahahaha ❤️
